Link Direction Made Case Insensitive
hamlet-io/engine pull request #1408
Opened 2020-10-06 07:49 UTC by RossMurr4y

## Description

Link processing functions to force all values lower-case.

## Motivation and Context

The requirement for lowercase is presently undocumented and unnecessary. Otherwise correctly-formatted links do not trigger errors, so template passes succeed, however they will be missing the intended permissions.

## How Has This Been Tested?

Local template generation and deployment.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Refactor (non-breaking change which improves the structure or operation of the implementation)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Followup Actions

- [x] None

## Checklist:

- [ ] My change requires a change to the [documentation](https://github.com/hamlet-io/docs).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] None of the above.

2020-10-06 21:38 UTC, ml019 requested changes

2020-10-06 21:38 UTC, ml019 commented on providers/shared/deploymentframeworks/default/legacy.ftl
> +                    "Direction" : direction?lower_case,
Unnecessary given change above

2020-10-06 23:23 UTC, RossMurr4y commented on providers/shared/deploymentframeworks/default/legacy.ftl
> +                    "Direction" : direction?lower_case,
Thanks @ml019 , have updated in 57c7e40

2020-10-07 08:50 UTC, ml019 approved these changes

2020-10-07 08:50 UTC, merged