Feature - APIGateway LogStore
hamlet-io/engine pull request #1417
Opened 2020-10-14 01:43 UTC by RossMurr4y

## Description

New attribute on the `apigateway` component - LogStore.

## Motivation and Context

Need to be able to define on the component which logging store the component logs should be setup for.

* Ultimately the LogProfiles should be able to define such settings however currently they do not. Further discussion around how logging profiles should look need to be had before that could be implemented however, so this attribute is an interim measure. Valid values are to be implemented by each provider.

## How Has This Been Tested?

Local template generation and deployment (alongside matching changes in the AWS provider plugin).

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which improves the structure or operation of the implementation)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Followup Actions

- [x] None

## Checklist:

- [ ] My change requires a change to the [documentation](https://github.com/hamlet-io/docs).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] None of the above.

2020-10-14 02:02 UTC, roleyfoley requested changes

2020-10-14 02:02 UTC, roleyfoley commented on providers/shared/components/apigateway/id.ftl
> +            },
What is the `destination` defined as? Is this the link Id? a specific type?

2020-10-21 04:14 UTC, RossMurr4y commented
@roleyfoley  I have re-implemented this new attribute to specifically direct the logs to OpsData. 

Whilst I don't love the attribute name, I intended for this to only be implemented until we can have a meeting with @ml019 and discuss loggingProfiles further.

2020-10-21 21:13 UTC, ml019 approved these changes
Based on this being subject to further refinement, no issue in merging.

2020-10-21 21:13 UTC, merged