fix(schema): metaparameters should not ref links
hamlet-io/engine pull request #1473
Opened 2020-11-25 04:54 UTC by RossMurr4y

## Description

Corrected the `metaparameter` scheme generation.

Note: I restructured the input object to reflect how it would appear as a `reference` or `component` composite object. This is in preparation for a subsequent PR to define metaparameters as their own data structure.

## Motivation and Context

The schema generation macro for this data type was incorrectly being told to reference metaparameters (itself) instead of defining its schema.

## How Has This Been Tested?

Local template generation

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which improves the structure or operation of the implementation)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Followup Actions

- [x] None

## Checklist:

- [ ] My change requires a change to the [documentation](https://github.com/hamlet-io/docs).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] None of the above.

2020-11-30 21:59 UTC, ml019 requested changes

2020-11-30 21:59 UTC, ml019 commented on providers/shared/views/schema/setup.ftl
>              [@addSchema
needs indenting

2020-12-06 23:53 UTC, RossMurr4y commented on providers/shared/views/schema/setup.ftl
>              [@addSchema
Fixup in 252b302

2020-12-06 23:53 UTC, RossMurr4y commented
@ml019 think this ones good to go?

2020-12-07 05:40 UTC, roleyfoley approved these changes

2020-12-07 05:40 UTC, merged