Refactor commandlineoptions
hamlet-io/engine pull request #1552
Opened 2021-02-19 05:15 UTC by ml019

## Description
 Introduce the mechanism for command line option seeding by entrances

## Motivation and Context
The commit builds on the refactor work for input sources and starts the transition to sourcing command line options from dynamic input state.

It defines the pattern by which entrances can provide any command line option seeding prior to the incoation of the entrance itself. This validation of the options prior to the entrnace being invoked. The `deployment` entrance is converted to this pattern. A subsequent change will convert the remainder of the entrances once the pattern has been validated.

It also ensures the global commandLineOption variable is kept up to date even if code is transitioned to use an input seeder rather than directly calling `addCommandLineOption`.

Depends on https://github.com/hamlet-io/engine/pull/1549 

## How Has This Been Tested?
Local template creation

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Refactor (non-breaking change which improves the structure or operation of the implementation)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Followup Actions
- [x] None

## Checklist:

- [ ] My change requires a change to the [documentation](https://github.com/hamlet-io/docs).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] None of the above.

2021-03-02 10:52 UTC, roleyfoley commented
@ml019 Is this PR now ready for review?

2021-03-04 07:30 UTC, roleyfoley commented
Will be replaced with a new one

2021-03-22 04:27 UTC, roleyfoley requested changes

2021-03-22 04:27 UTC, roleyfoley commented on providers/shared/layers/layer.ftl
> +[#assign REGION_LAYER_REFERENCE_TYPE = "Segments" ]
Should these values be Region and Regions?

2021-03-22 04:27 UTC, roleyfoley commented on engine/inputdata/commandLineOptions.ftl
> +
Should these all be namespaced to getCLO  instead of just a couple?

2021-03-22 04:56 UTC, RossMurr4y commented
Performed local testing and schema generation against this and matching provider PRs and all were successful.

2021-03-24 00:33 UTC, roleyfoley approved these changes

2021-03-24 00:33 UTC, merged