feat: add filter policies to topic subscriptions
hamlet-io/engine pull request #1850
Opened 2021-11-02 06:17 UTC by ken9ross

## Intent of Change

- New feature (non-breaking change which adds functionality)
Add filter policy to topic subscriptions

## Description

New child attribute of Filters for Subscriptions

## Motivation and Context

Required for https://github.com/gs-dawr/exdoc-mail-aws/issues/49

## How Has This Been Tested?

Local generation, not deployed to AWS

## Related Changes

### Prerequisite PRs:

- None

### Dependent PRs:

- None

### Consumer Actions:

- None

2021-11-09 07:47 UTC, roleyfoley requested changes

2021-11-11 01:54 UTC, ken9ross commented on providers/shared/components/topic/id.ftl
> +                        "Names" : "MsgKey",
Done

2021-11-11 01:54 UTC, ken9ross commented on providers/shared/components/topic/id.ftl
> +                        "Names" : "MsgValues",
Done

2021-11-11 03:24 UTC, roleyfoley approved these changes

2021-11-11 03:28 UTC, merged