Add support for WAFv2
hamlet-io/engine pull request #1862
Opened 2021-11-16 05:27 UTC by ken9ross

## Intent of Change

- New feature (non-breaking change which adds functionality)

## Description

Add support for WAFv2 controlled by Version attribute

## Motivation and Context

Required for https://github.com/hamlet-io/engine/issues/1768

## How Has This Been Tested?

Locally generated and deployed to AWS

## Related Changes

### Prerequisite PRs:

- None

### Dependent PRs:

- None

### Consumer Actions:

- None

2021-11-19 08:04 UTC, ml019 requested changes

2021-11-19 08:04 UTC, ml019 commented on providers/shared/components/component.ftl
> +            "Values" : [ "V1","V2"],
Please use lowercase for versions

2021-11-22 02:28 UTC, ken9ross commented on providers/shared/components/component.ftl
> +            "Values" : [ "V1","V2"],
Done

2021-11-22 22:17 UTC, ml019 approved these changes

2021-11-22 22:17 UTC, merged