feat: standard configuration storage
hamlet-io/engine pull request #1874
Opened 2021-12-08 22:01 UTC by roleyfoley

## Intent of Change

- New feature (non-breaking change which adds functionality)

## Description

- Adds a standardised configuration store to provide a definitive store of the configuration available in hamlet
- Updates calls to get configuration to use helper functions instead of direct calls to global variables
- Removes the plural type from the attribute set configuration as it is not required

## Motivation and Context

The key motivation for this is to create a central standardised store of the configuration available to hamlet. This can be used to enforce and document a fixed schema throughout hamlet. On top of this it should be possible to also determine the source of configurations that have been added through plugins, which is where most of our configuration comes from. 

## How Has This Been Tested?

Tested locally 

## Related Changes

### Prerequisite PRs:

- None

### Dependent PRs:

- None

### Consumer Actions:

- None

2021-12-08 22:16 UTC, ml019 commented
Need to understand how this interacts with dynamic CMDB loading and cross-solution linking. A lot of this configuration is not a singleton but varies as the context changes with following the link.

2021-12-08 22:19 UTC, roleyfoley commented
The next step after this is to add the source plugin for each configuration set. This would allow for each plugin to add their configuration sets and then when the configuration is looked up filters can be applied to control what the effective result would be.

2021-12-16 00:13 UTC, ml019 requested changes
I think I get the idea. No mention of config being provider specific but I guess we can evolve if that seems necessary.

2021-12-16 00:13 UTC, ml019 commented on providers/shared/views/schemaset/setup.ftl
> +                [#local schemas = getModuleConfiguration?keys ]
```suggestion
                [#local schemas = getModuleConfiguration()?keys ]
```

2021-12-16 00:24 UTC, roleyfoley commented
Yeah that is the next PR once this is merged. That is potentially the split between provider and plugin...

2021-12-16 00:41 UTC, ml019 approved these changes

2021-12-16 00:41 UTC, merged