feat: add support for dynamic value evaulation
hamlet-io/engine pull request #2009
Opened 2022-06-10 00:01 UTC by roleyfoley

## Intent of Change

- New feature (non-breaking change which adds functionality)

## Description

- Adds support for resolve configuration attribute values using dynamic references to other properties within the CMDB

## Motivation and Context

## How Has This Been Tested?

## Related Changes

### Prerequisite PRs:

- None

### Dependent PRs:

- None

### Consumer Actions:

- None

2022-06-11 12:17 UTC, ml019 requested changes

2022-06-11 12:17 UTC, ml019 commented on engine/provider.ftl
> +            [#-- Determine the tasks for the provider --]
```suggestion
            [#-- Determine the dynamic value providers for the provider --]
```

2022-06-14 00:36 UTC, ml019 commented
@roleyfoley wondering why you dismissed the comment change I proposed? The comment looks like a cut/paste duplication.

2022-06-14 01:19 UTC, roleyfoley commented
Was a rebase with a force push must have missed that change syncing it locally

2022-06-14 04:42 UTC, ml019 approved these changes

2022-06-14 04:42 UTC, merged