fix(dynamicvalue): remove fatal on missing link
hamlet-io/engine pull request #2023
Opened 2022-07-09 09:49 UTC by roleyfoley

## Intent of Change

- Bug fix (non-breaking change which fixes an issue)

## Description

- When a link cannot be found for an attribute dynamicvalue don't raise a fatal error as it might not be deployed yet

## Motivation and Context

Fatal error stopping the ability to deploy the component that hasn't been deployed

## How Has This Been Tested?

tested locally

## Related Changes

### Prerequisite PRs:

- None

### Dependent PRs:

- None

### Consumer Actions:

- None

2022-07-10 05:58 UTC, ml019 requested changes

2022-07-10 05:58 UTC, ml019 commented on providers/shared/dynamicvalues/attribute/dynamicvalue.ftl
>      [#return "__${vaule}__"]
Looks like a typo?

2022-07-10 08:56 UTC, roleyfoley commented on providers/shared/dynamicvalues/attribute/dynamicvalue.ftl
>      [#return "__${vaule}__"]
fixed

2022-07-12 00:00 UTC, ml019 approved these changes

2022-07-12 00:00 UTC, merged